{ lib, config, pkgs, ... }:

with lib;

let
  cfg = config.modules.programs.caelestia;

  # Script to sync Caelestia colors to Nix configuration
  caelestia-nix-sync = pkgs.writeShellScriptBin "caelestia-nix-sync" ''
    #!/usr/bin/env bash
    set -euo pipefail

    SCHEME_FILE="''${XDG_STATE_HOME:-$HOME/.local/state}/caelestia/scheme.json"
    COLORS_NIX="$HOME/.config/nixos/caelestia-colors.nix"

    if [ ! -f "$SCHEME_FILE" ]; then
      echo "Error: No caelestia scheme found at $SCHEME_FILE"
      echo "Run 'caelestia wallpaper <image>' first to generate a color scheme"
      exit 1
    fi

    echo "Reading colors from Caelestia scheme..."

    # Extract colors and convert to Nix attribute set
    cat > "$COLORS_NIX" << 'EOF'
    # Auto-generated by caelestia-nix-sync
    # DO NOT EDIT MANUALLY - this file is regenerated when you change wallpapers
    {
      colours = {
    EOF

    ${pkgs.jq}/bin/jq -r '.colours | to_entries | .[] | "    \(.key) = \"\(.value)\";"' "$SCHEME_FILE" >> "$COLORS_NIX"

    cat >> "$COLORS_NIX" << EOF
      };
      mode = "$(${pkgs.jq}/bin/jq -r '.mode' "$SCHEME_FILE")";
      variant = "$(${pkgs.jq}/bin/jq -r '.variant' "$SCHEME_FILE")";
    }
    EOF

    echo "✓ Colors synced to $COLORS_NIX"
    echo ""
    echo "Current scheme:"
    echo "  Mode: $(${pkgs.jq}/bin/jq -r '.mode' "$SCHEME_FILE")"
    echo "  Variant: $(${pkgs.jq}/bin/jq -r '.variant' "$SCHEME_FILE")"
    echo ""
    echo "To apply these colors to your NixOS configuration:"
    echo "  1. Import caelestia-colors.nix in your modules"
    echo "  2. Run 'sudo nixos-rebuild switch' or 'home-manager switch'"
    echo ""
    echo "Or add this to your wallpaper post-hook in ~/.config/caelestia/cli.json:"
    echo "  \"postHook\": \"<your-wallpaper-command> && caelestia-nix-sync && home-manager switch\""
  '';
in
{
  config = mkIf cfg.enable {
    home.packages = [ caelestia-nix-sync ];
  };
}
