# Set delay between prefix and command
set -sg escape-time 1

# Set prefix to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "tmux.conf reloaded"

# Set the base index for windows and panes to 1
set -g base-index 1
setw -g pane-base-index 1

#remap some key bindings
#easy recall splits
bind | split-window -h
bind - split-window -v

#add vim nav in panes
bind h select-pane -L 
bind j select-pane -D 
bind k select-pane -U 
bind l select-pane -R

#cycle panes
bind -r C-j select-pane -t :.-
bind -r C-k select-pane -t :.+

#cycle windows
#bind -r C-h select-window -t :-
#bind -r C-l select-window -t :+

#resize windows
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

#enable mouse
set -g mouse on

# Toggle mouse on
bind m \
  set -g mouse on \;\
  display 'Mouse: ON'

# Toggle mouse off
bind M \
  set -g mouse off \;\
  display 'Mouse: OFF'

#use the system clipboard
# bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard > /dev/null"
#if using the mouse you can hold shift to access the system clipboard

# To use native cut and paste toggle the mouse off then zoom the pane
# using the toggle prefix z. 

# copy to wayland clipboard
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
bind p run "wl-paste --no-newline | tmux load-buffer - ; tmux paste-buffer"
set-window-option -g mode-keys vi


set -g history-limit 10000

set -g status on
set -g focus-events on


set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -ga terminal-overrides ",*:RGB"

# Allow passthrough for terminal transparency
set -g allow-passthrough on

#monitor activity
setw -g monitor-activity on 
set -g visual-activity on


# TokyoNight colors for Tmux

set -g mode-style "fg=color4,bg=color8"

set -g message-style "fg=color4,bg=color8"
set -g message-command-style "fg=color4,bg=color8"

set -g pane-border-style "fg=color8"
set -g pane-active-border-style "fg=color4"

set -g window-style "bg=default"
set -g window-active-style "bg=default"

set -g status "on"
set -g status-justify "left"

set -g status-style "fg=color4,bg=color0"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=color0,bg=color4,bold] #S #[fg=color4,bg=color0,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=color0,bg=color0,nobold,nounderscore,noitalics]#[fg=color4,bg=color0] #{prefix_highlight} #[fg=color8,bg=color0,nobold,nounderscore,noitalics]#[fg=color4,bg=color8] %Y-%m-%d  %I:%M %p #[fg=color4,bg=color8,nobold,nounderscore,noitalics]#[fg=color0,bg=color4,bold] #h "
if-shell '[ "$(tmux show-option -gqv "clock-mode-style")" == "24" ]' {
  set -g status-right "#[fg=color0,bg=color0,nobold,nounderscore,noitalics]#[fg=color4,bg=color0] #{prefix_highlight} #[fg=color8,bg=color0,nobold,nounderscore,noitalics]#[fg=color4,bg=color8] %Y-%m-%d  %H:%M #[fg=color4,bg=color8,nobold,nounderscore,noitalics]#[fg=color0,bg=color4,bold] #h "
}

setw -g window-status-activity-style "underscore,fg=color7,bg=color0"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=color7,bg=color0"
setw -g window-status-format "#[fg=color0,bg=color0,nobold,nounderscore,noitalics]#[default] #I  #W #F #[fg=color0,bg=color0,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=color0,bg=color8,nobold,nounderscore,noitalics]#[fg=color4,bg=color8,bold] #I  #W #F #[fg=color8,bg=color0,nobold,nounderscore,noitalics]"

# tmux-plugins/tmux-prefix-highlight support
# set -g @prefix_highlight_output_prefix "#[fg=#e0af68]#[bg=color0]#[fg=color0]#[bg=#e0af68]"
# set -g @prefix_highlight_output_suffix ""
